### ISSUE TITLE
Not useful error when you have an invalid manifest.yml

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#141]
I had an invalid manifest.yml

```yaml
group: "atomist-rugs"
artifact: "rug-project"
version: "0.1.0"
requires: "[0.12.0,1.0.0)"
dependencies:
- "atomist-rugs:rug-editors": "0.11.0"
```

When I ran the CLI, the error was:

```
$ rug shell -l

java.util.LinkedHashMap cannot be cast to java.lang.String
```

Could it be improved to say the manifest.yml is invalid?
